' @file      ClassDiagram_JDBC_children_update.pu
' @brief     クラス図出力用のファイル
' @note      高度情報演習2C 後半 木村教授担当分 Team3
' @auther    AL18036 Kataoka Nagi
' @date      2020-12-31 02:59:36
' $Version   1.2
' $Revision  1.5
' @par       編集：JavaFX関係をコメントアウト
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe ClassDiagram_JDBC_children_update.pu -charset UTF-8
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml ./out/ClassDiagram_JDBC_children_update.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

header 
Team 3 : AL18036 Kataoka Nagi
2020-12-31 03:00:49
編集：JavaFX関係をコメントアウト
end header

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**Kodo 2C Team 3: ClassDiagram_JDBC_children_update**
+ public
~- private
end title
' __static__

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package src {
  package src.application {
    class Main
  }
  package src.gameprocess {
  }
  package src.jdbc {
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

note left
  --Folder Tree--
  2C_team3
  |_ src
    |_ application
      |_ application.css
      |_ Battle.fxml
      |_ Menu.fxml
      |_ BattleController.java
      |_ Main.java
      |_ MenuController.java
    |_ gameprocess
      |_ BattleManager.java
    |_ jdbc
      |_ DBConnector.java
      |_ DataAccessObject.java
      |_ MenuDAO.java
      |_ BattleDAO.java
      |_ ShapnessSearchDAO.java
      |_ PlayerStatusSearchDAO.java
      |_ MonsterAttackStatusSearchDAO.java
      |_ PlayerHpDAO.java
      |_ MonsterMainHpDAO.java
      |_ MonsterPartsHpDAO.java
      |_ sql
        |_ hoge.sql
        |_ fuga.sql
  |_ bin/application
    |_ ~*.class
end note

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package java.sql {
}

' package javafx {
'   class Application
'   Interface Initializable
' }

src.jdbc --+ java.sql
' src.application --+ javafx

''''''''''''''''''''''''''''''''''''''''''''''''''

' @note クラスの命名規則
' @see  https://qiita.com/KeithYokoma/items/ee21fec6a3ebb5d1e9a8

package src.application {
}

' 記事のクラス
  ' class ApplicationController extends Initializable {
  '   - dropDown: ChoiceBox<String>
  '   - textBox: TextField
  '   - button: Button

  '   + initialize(location: URL, resources: ResourceBundle): void
  '   + onClick(event: ActionEvent): void
  '   + getToolType(): ChoiceBox<String>
  '   + setToolType(toolType: ChoiceBox<String>): void
  '   + getInputFile(): TextField
  '   + setInputFile(textBox: TextField): void
  '   + getReference(): Button
  '   + setReference(button: Button): void
  ' }


''''''''''''''''''''''''''''''''''''''''''''''''''

package src.gameprocess {
}

''''''''''''''''''''''''''''''''''''''''''''''''''

package src.jdbc {
  ' @note DAO pattern
  ' @see https://kanda-it-school-kensyu.com/java-jdbc-contents/jj_ch04/jj_0401/

  abstract class BattleDAO {
  }

  class PlayerHpDAO extends BattleDAO {
    - TABLE_NAME: final String
    - PRIMARY_KEY_COLUMN_NAME: final String

    + PlayerHpDAO(weaponName: String, armorName: String, monsterName: String) {
    - createPlayerHpTable(): void
    - createPlayerHpIdx(): void
    + dropPlayerHpTable(): void
    + selectFirstPlayerHp(): int
    + updateFirstPlayerHp(playerHp: int): void
  }

  class MonsterMainHpDAO extends BattleDAO {
    - TABLE_NAME: final String
    - PRIMARY_KEY_COLUMN_NAME: final String

    + MonsterMainHpDAO(weaponName: String, armorName: String, monsterName: String) {
    - createMonsterMainHpTable(): void
    - createMonsterMainHpIdx(): void
    + dropMonsterMainHpTable(): void
    + selectFirstMonsterMainHp(): int
    + updateFirstMonsterMainHp(monsterMainHp: int): void
  }

  class MonsterPartsHpDAO extends BattleDAO {
    - TABLE_NAME: final String
    - PRIMARY_KEY_COLUMN_NAME: final String

    + MonsterPartsHpDAO(weaponName: String, armorName: String, monsterName: String)
    - createMonsterPartsHpTable() : void
    - createMonsterPartsHpIdx() : void
    + dropMonsterPartsHpTable() : void
    + selectAllMonsterPartsName(): ArrayList<String>
    + selectAllMonsterPartsHp(): ArrayList<Integer>
    + selectAllMonsterPartsHardness(): ArrayList<Integer>
    + updateMonsterPartsName(monsterPartsName: String, primaryKey: String): void
    + updateMonsterPartsHp(monsterPartsHp: int, primaryKey: String) : void
    + updateMonsterPartsHardness(monsterPartsHardness: int, primaryKey: String) : void
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@enduml
