' @file      ClassDiagram_JDBC_children_search.pu
' @brief     クラス図出力用のファイル
' @note      高度情報演習2C 後半 木村教授担当分 Team3
' @auther    AL18036 Kataoka Nagi
' @date      2020-12-31 03:00:18
' $Version   1.2
' $Revision  1.3
' @par       編集：JavaFX関係をコメントアウト
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe ClassDiagram_JDBC_children_search.pu -charset UTF-8
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml ./out/ClassDiagram_JDBC_children_search.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

header 
Team 3 : AL18036 Kataoka Nagi
2020-12-31 03:00:49
編集：JavaFX関係をコメントアウト
end header

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**Kodo 2C Team 3: ClassDiagram_JDBC_children_search**
+ public
~# protected
~- private
end title
' __static__

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package src {
  package src.application {
    class Main
  }
  package src.gameprocess {
  }
  package src.jdbc {
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

note left
  --Folder Tree--
  2C_team3
  |_ src
    |_ application
      |_ application.css
      |_ Battle.fxml
      |_ Menu.fxml
      |_ BattleController.java
      |_ Main.java
      |_ MenuController.java
    |_ gameprocess
      |_ BattleManager.java
    |_ jdbc
      |_ DBConnector.java
      |_ DataAccessObject.java
      |_ MenuDAO.java
      |_ BattleDAO.java
      |_ ShapnessSearchDAO.java
      |_ PlayerStatusSearchDAO.java
      |_ MonsterAttackStatusSearchDAO.java
      |_ PlayerHpDAO.java
      |_ MonsterMainHpDAO.java
      |_ MonsterPartsHpDAO.java
      |_ consts
        |_ ColumnName.java
        |_ Consts.java
        |_ DenormalizedTableName.java
        |_ IdxName.java
        |_ NormalizedTableName.java
        |_ TableName.java
      |_ utils
        |_ DebugUtil.java
      |_ sql
        |_ hoge.sql
        |_ fuga.sql
  |_ bin/application
    |_ ~*.class
end note

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package java.sql {
}

' package javafx {
'   class Application
'   Interface Initializable
' }

package src.jdbc {
  package src.jdbc.consts {
  }
}

src.jdbc --+ java.sql
' src.application --+ javafx

''''''''''''''''''''''''''''''''''''''''''''''''''

' @note クラスの命名規則
' @see  https://qiita.com/KeithYokoma/items/ee21fec6a3ebb5d1e9a8

package src.application {
}

' 記事のクラス
  ' class ApplicationController extends Initializable {
  '   - dropDown: ChoiceBox<String>
  '   - textBox: TextField
  '   - button: Button

  '   + initialize(location: URL, resources: ResourceBundle): void
  '   + onClick(event: ActionEvent): void
  '   + getToolType(): ChoiceBox<String>
  '   + setToolType(toolType: ChoiceBox<String>): void
  '   + getInputFile(): TextField
  '   + setInputFile(textBox: TextField): void
  '   + getReference(): Button
  '   + setReference(button: Button): void
  ' }


''''''''''''''''''''''''''''''''''''''''''''''''''

package src.gameprocess {
}

''''''''''''''''''''''''''''''''''''''''''''''''''

package src.jdbc {
  ' @note DAO pattern
  ' @see https://kanda-it-school-kensyu.com/java-jdbc-contents/jj_ch04/jj_0401/
  abstract class BattleDAO {
  }

  class SharpnessSearchDAO extends BattleDAO {
    ' - TABLE_NAME: final String
    ' - PRIMARY_KEY_COLUMN_NAME: final String

    + SharpnessSearchDAO(weaponName: String, armorName: String, monsterName: String)
    - createSharpnessSearchTable(): void
    - createSharpnessSearchIdx(): void
    + dropSharpnessSearchTable(): void
    + selectAllSharpnessColorName(): ArrayList<String>
    + selectAllSharpnessGaugeAmount(): ArrayList<Integer>
    + selectAllSharpnessIncreasingAttackValueRate(): ArrayList<Float>
  }

  class PlayerStatusSearchDAO extends BattleDAO {
    ' - TABLE_NAME: final String
    ' - PRIMARY_KEY_COLUMN_NAME: final String

    + PlayerStatusSearchDAO(weaponName: String, armorName: String, monsterName: String)
    - createPlayerStatusSearchTable(): void
    - createPlayerStatusSearchIdx(): void
    + dropPlayerStatusSearchTable(): void
    + selectFirstWeaponCode(): String
    + selectFirstWeaponName(): String
    + selectFirstWeaponAttackVal(): int
    + selectFirstWeaponCriticalRate(): float
    + selectFirstWeaponElementVal(): int
    + selectFirstWeaponElementCode(): String
    + selectFirstWeaponElementName(): String
    + selectFirstArmorCode(): String
    + selectFirstArmorName(): String
    + selectFirstArmorDiffenceVal(): int
    + selectFirstArmorSkillCode(): String
    + selectFirstArmorSkillName(): String
    + selectFirstArmorIncreasingSkillTarget(): String
    + selectFirstArmorIncreasingSkillVal(): int
    + selectFirstArmorElementResistanceCode(): String
    + selectFirstArmorFireResistance(): int
    + selectFirstArmorWaterResistance(): int
    + selectFirstArmorElectricResistance(): int
    + selectFirstArmorIceResistance(): int
    + selectFirstArmorDragonResistance(): int
  }

  class MonsterAttackStatusSearchDAO extends BattleDAO {
    ' - FROM_TABLE_NAME: final String
    ' - TABLE_NAME: final String
    ' - PRIMARY_KEY_COLUMN_NAME: final String
    ' - MONSTER_ATTACK_NAME: final String
    ' - MONSTER_ATTACK_VAL: final String
    ' - MONSTER_ATTACK_MISS_PROB: final String

    + MonsterAttackStatusSearchDAO(weaponName: String, armorName: String, monsterName: String)
    - MonsterAttackStatusSearchTable(): void
    - createMonsterAttackStatusSearchIdx(): void
    + dropMonsterAttackStatusSearchTable(): void
    + selectAllMonsterAttackName(): ArrayList<String>
    + selectAllMonsterAttackVal(): ArrayList<Integer>
    + selectAllMonsterAttackMissProb(): ArrayList<Float>
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@enduml
