' @file      ClassDiagram_GUI_and_GameProess.pu
' @brief     クラス図出力用のファイル
' @note      高度情報演習2C 後半 木村教授担当分 Team3
' @auther    AL18036 Kataoka Nagi
' @date      2020-12-28 07:26:13
' $Version   1.2
' $Revision  1.0
' @par       修正：DAOの部分を別ファイルに移動
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe ClassDiagram_GUI_and_GameProess.pu -charset UTF-8
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml ./out/ClassDiagram_GUI_and_GameProess.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

header 
Team 3 : AL18036 Kataoka Nagi
2020-12-28 07:26:50
修正：DAOの部分を別ファイルに移動
end header

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**Kodo 2C Team 3: ClassDiagram_GUI_and_GameProess**
+ public
~# protected
~- private
end title
' __static__

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package src {
  package src.application {
    class Main
  }
  package src.gameprocess {
  }
  package src.jdbc {
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

note left
  --Folder Tree--
  2C_team3
  |_ src
    |_ application
      |_ application.css
      |_ Battle.fxml
      |_ Menu.fxml
      |_ BattleController.java
      |_ Main.java
      |_ MenuController.java
    |_ gameprocess
      |_ BattleManager.java
    |_ jdbc
      |_ DBConnector.java
      |_ DataAccessObject.java
      |_ MenuDAO.java
      |_ BattleDAO.java
      |_ ShapnessSearchDAO.java
      |_ PlayerStatusSearchDAO.java
      |_ MonsterAttackStatusSearchDAO.java
      |_ PlayerHpDAO.java
      |_ MonsterMainHpDAO.java
      |_ MonsterPartsHpDAO.java
      |_ consts
        |_ ColumnName.java
        |_ Consts.java
        |_ DenormalizedTableName.java
        |_ IdxName.java
        |_ NormalizedTableName.java
        |_ TableName.java
      |_ utils
        |_ DebugUtil.java
      |_ sql
        |_ hoge.sql
        |_ fuga.sql
  |_ bin/application
    |_ ~*.class
end note

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package java.sql {
}

package javafx {
  class Application
  Interface Initializable
}

package src.jdbc {
  package src.jdbc.consts {
  }
}

src.jdbc --+ java.sql
src.application --+ javafx

''''''''''''''''''''''''''''''''''''''''''''''''''

' @note クラスの命名規則
' @see  https://qiita.com/KeithYokoma/items/ee21fec6a3ebb5d1e9a8

package src.application {
  ' @note Scene Builder (GUI tool)
  ' @see  https://qiita.com/tarosa0001/items/05ac653a091b7d1290f9
  class Main extends Application {
    + start(primaryStage: Stage): void
    + {static} main(args: String[]): void
  }
  
  class MenuController {
    - weapon_field: ComboBox<String>
    - armor_field: ComboBox<String>
    - monster_field: ComboBox<String>
    -  StartButton: Button
    -  EndButton: Button
    -  Attack_value: Label
    -  Defense_value: Label

    # OnEndButton(event: ActionEvent): void
    # OnStartButton(event: ActionEvent): void
    # selectArmor(event: ActionEvent): void
    # selectWeapon(event: ActionEvent): void
  }

  class BattleController {
    - Attack_Log: Label
    - HP_Value: Label
    - Sharpmess_Value: Label
    - AttackButton: Button
    
    # OnAttackButton(event: ActionEvent): void
  }
}

' 記事のクラス
  ' class ApplicationController extends Initializable {
  '   - dropDown: ChoiceBox<String>
  '   - textBox: TextField
  '   - button: Button

  '   + initialize(location: URL, resources: ResourceBundle): void
  '   + onClick(event: ActionEvent): void
  '   + getToolType(): ChoiceBox<String>
  '   + setToolType(toolType: ChoiceBox<String>): void
  '   + getInputFile(): TextField
  '   + setInputFile(textBox: TextField): void
  '   + getReference(): Button
  '   + setReference(button: Button): void
  ' }


''''''''''''''''''''''''''''''''''''''''''''''''''

package src.gameprocess {
  class BattleManager {
    - monster_id: int
    - element_player: int
    - elementValue_player: int
    - rnd: Random

    + PlayerAttack(Parts_id: int): void
    - MonsterAttack(): void
    - ElementDamage_PlayerAttack(): float
    - ElementCompatibilityCalculation_EnemyAttack(attackElement: int): float
    - AddLog(addText: String): void
    - SharpnessDecrease(sharpness: int): int 
  }

  class EquipmentManager {
    + GetAttack(weaponName: String): int
    + GetDeffence(equipmentName: String): int
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''

package src.jdbc {
  ' @note DAO pattern
  ' @see https://kanda-it-school-kensyu.com/java-jdbc-contents/jj_ch04/jj_0401/
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@enduml
