' @file      class_diagram.pu
' @brief     クラス図出力用のファイル
' @note      高度情報演習2C 後半 木村教授担当分 Team3
' @auther    AL18036 Kataoka Nagi
' @date      2020-12-27 22:23:30
' $Version   1.0
' $Revision  1.6
' @par       変更点：closeDBResourcesメソッドを編集
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe class_diagram.pu
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml ./class_diagram.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

header 
Team 3 : AL18036 Kataoka Nagi
2020-12-27 22:11:01
Edit: closeDBResources
end header

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**Kodo 2C Team 3: Class Diagram**
+ public
~- private
end title
' __static__

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package src {
  package src.application {
    class Main
  }
  package src.gameprocess {
  }
  package src.jdbc {
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

note left
  --Folder Tree--
  2C_team3
  |_ src
    |_ application
      |_ application.css
      |_ Battle.fxml
      |_ Menu.fxml
      |_ BattleController.java
      |_ Main.java
      |_ MenuController.java
    |_ gameprocess
      |_ BattleManager.java
    |_ jdbc
      |_ DBConnector.java
      |_ DataAccessObject.java
      |_ MenuDAO.java
      |_ BattleDAO.java
      |_ sql
        |_ hoge.sql
        |_ fuga.sql
  |_ bin/application
    |_ ~*.class
end note

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

package java.sql {
}

package javafx {
  class Application
  Interface Initializable
}

src.jdbc --+ java.sql
src.application --+ javafx

''''''''''''''''''''''''''''''''''''''''''''''''''

' @note クラスの命名規則
' @see  https://qiita.com/KeithYokoma/items/ee21fec6a3ebb5d1e9a8

package src.application {
  ' @note Scene Builder (GUI tool)
  ' @see  https://qiita.com/tarosa0001/items/05ac653a091b7d1290f9
  class Main extends Application {
    + start(primaryStage: Stage): void
    + {static} main(args: String[]): void
  }
  
  class MenuController {
    - weapon_field: ComboBox<String>
    - armor_field: ComboBox<String>
    - monster_field: ComboBox<String>
    -  StartButton: Button
    -  EndButton: Button
    -  Attack_value: Label
    -  Defense_value: Label

    # OnEndButton(event: ActionEvent): void
    # OnStartButton(event: ActionEvent): void
    # selectArmor(event: ActionEvent): void
    # selectWeapon(event: ActionEvent): void
  }

  class BattleController {
    - Attack_Log: Label
    - HP_Value: Label
    - Sharpmess_Value: Label
    - AttackButton: Button
    
    # OnAttackButton(event: ActionEvent): void
  }
}

' 記事のクラス
  ' class ApplicationController extends Initializable {
  '   - dropDown: ChoiceBox<String>
  '   - textBox: TextField
  '   - button: Button

  '   + initialize(location: URL, resources: ResourceBundle): void
  '   + onClick(event: ActionEvent): void
  '   + getToolType(): ChoiceBox<String>
  '   + setToolType(toolType: ChoiceBox<String>): void
  '   + getInputFile(): TextField
  '   + setInputFile(textBox: TextField): void
  '   + getReference(): Button
  '   + setReference(button: Button): void
  ' }


''''''''''''''''''''''''''''''''''''''''''''''''''

package src.gameprocess {
  class BattleManager {
    - monster_id: int
    - element_player: int
    - elementValue_player: int
    - rnd: Random

    + PlayerAttack(Parts_id: int): void
    - MonsterAttack(): void
    - ElementDamage_PlayerAttack(): float
    - ElementCompatibilityCalculation_EnemyAttack(attackElement: int): float
    - AddLog(addText: String): void
    - SharpnessDecrease(sharpness: int): int 
  }

  class EquipmentManager {
    + GetAttack(weaponName: String): int
    + GetDeffence(equipmentName: String): int
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''

package src.jdbc {
  ' @note DAO pattern
  ' @see https://kanda-it-school-kensyu.com/java-jdbc-contents/jj_ch04/jj_0401/

  abstract class DBConnector {
    - {static} RDB_DRIVE: final String
    - {static} URL: final String
    - {static} USER: final String
    - {static} PASSWD: final String

    + {static} getConnection(): Connection
  }

  abstract class DataAccessObject extends DBConnector {
    # selectColumn(columnName: String, tableName: String, primaryKeyColumnName: String): ArrayList<String>
    # toIntegerList(strList: ArrayList<String>): ArrayList<Integer>
    # createTable(tableName: String): void
    # dropTable(tableName: String): void
    # closeDBResources(resultSet: ResultSet, statement: Statement, connection: Connection)
  }

  class MenuDAO extends DataAccessObject {
    + MenuDAO(): void
    + selectAllWeaponName(): ArrayList<String>
    + selectAllArmorName(): ArrayList<String>
    + selectAllMonsterName(): ArrayList<String>
    + selectAllWeaponAttackVal(): ArrayList<Integer>
    + selectAllArmorDiffenceVal(): ArrayList<Integer>
  }

  abstract class BattleDAO extends DataAccessObject {
    + BattleDAO(weaponName: String, armorName: String, monsterName: String): void
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



''''''''''''''''''''''''''''''''''''''''''''''''''


' ********** PlantUML Sample **********

' class ClassName

' note left
'   --Folder Tree--
'   2C_team3
'   |_ src
'     |_ foo.java
'     |_ bar.java
'   |_ out
'     |_ foo.class
'     |_ bar.class
'   |_ sql
'     |_ hoge.sql
'     |_ fuga.sql
'   |_ lib
'     |_ piyo.jar
' end note

' class ClassName implements Interface {
'   - fieldName: Type = Value

'   + methodName(): Returns
' }


' class Use {
' }

' class ClassName extends Extends {
' }

' ClassName ..> Use

' ********** PlantUML Tutorial **********

' note left

'   --木構造--
'   |_build.gradle
'   |_src
'     |_main
'       |_java
'         |_**bold**
'         |_--strike--
'         |_//itaric//
'         |___underline__
'         |_""monospace""
'     |_test

' end note

' class Hello　<<StereoType>> {
'     {abstract} one: String
'     {static} three(param1: String, param2: int): boolean
'     String two
'     int four(List<String> param)
' }
' class World <Template>{
'     - privateField: int
'     # protectedField: int
'     ~ packagePrivateField: int
'     + publicField: int

'     - privateMethod(): void
'     # protectedMethod(): void
'     ~ packagePrivateMethod(): void
'     + publicMethod(): void
' }
' note left : note
' note top of Hello: note

' interface hoge
' abstruct class hoge
' enum HelloWorld {
'     ONE
'     TWO
'     THREE
' }

' interface One
' interface Two
' interface Three extends Two
' interface Four
' class Five implements One, Three
' class Six extends Five implements Four {
'     field: String
'     method(): void
' }

' Hello -- World
' One --> Two
' Three <-- Four
' Five <--> Six
' Seven x-- Eight
' Nine --x Ten
' One ..> Two
' Three <.. Four
' One --|> Two
' Three <|-- Four
' One ..|> Two
' Three <|.. Four
' One --o Two
' Three o-- Four
' One --* Two
' Three *-- Four
' One -- Two : Hoge
' Three -- Four : Fuga >
' Five -- Six : < Piyo
' One "Foo" -- Two 
' Three -- "Bar" Four
' Five "1" -- "1..*" Six
' Seven "1 Fizz" -- "~* Buzz" Eight

' package one.two {
'     class Hello
' }
' package three.four {
'     World -- Hello
' }

' Hello -- World
' note on link
' hoge
' fuga
' end note

@enduml
